services:
  cantaloupe:
    image: uclalibrary/cantaloupe:5.0.7-0
    container_name: cantaloupe_server
    ports:
      - "8182:8182"
    volumes:
      - ./config/cantaloupe.properties:/home/cantaloupe/cantaloupe.properties
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - kali-net
    environment:
      # Java Opts
      JAVA_OPTS: >
        -Xms512m
        -Xmx2g
        -Dcantaloupe.config=/home/cantaloupe/cantaloupe.properties
        -Daws.accessKeyId=${AWS_ACCESS_KEY_ID}
        -Daws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
        -Daws.region=${AWS_REGION}

      # Need Admin UI for development?
      ENDPOINT_ADMIN_ENABLED: "${ENDPOINT_ADMIN_ENABLED}"
      ENDPOINT_ADMIN_USERNAME: "${ENDPOINT_ADMIN_USERNAME}"
      ENDPOINT_ADMIN_SECRET: "${ENDPOINT_ADMIN_SECRET}"

      # Set to debug on development
      LOG_APPLICATION_LEVEL: "${LOG_APPLICATION_LEVEL}"

      # Create Nginx vHost and SSL cert from ACME companion
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
      VIRTUAL_PORT: 8182

networks:
  kali-net:
    external: true
